/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Progress;

import java.awt.Font;
/**
 *
 * @author i62cumuj
 */
public class progressCircleBar extends javax.swing.JPanel {
    public int progress;
    /**
     * Creates new form progressCircleBar
     */
    public progressCircleBar() {
        initComponents();
    }

    public void setProgress(int i){
        this.progress=i;
        jLabel1.setText(String.valueOf(i)+"%");
        i=(i/10);
        int j=i*10;
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Progress/IMAGENES/"+j+".png")));
    }
    
    public int getProgress(){
        return progress;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("0%");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        jLabel1.setFont(new Font("Serif", Font.PLAIN, 15));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Progress/IMAGENES/0.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
