/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Termometro;
/**
 *
 * @author Usuario
 */
public class Termometro extends javax.swing.JPanel {
    private double temperature;
    /**
     * Creates new form Termometro
     */
    public Termometro(double base) {
        initComponents();
        setTemperature(base);
        
    }
    public void setTemperature(double b){
        temperature=b;
        if(temperature<20){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Termometro/IMAGENES/1.png"))); // NOI18N
        }
        else if(temperature<30&&temperature>=20){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Termometro/IMAGENES/2.png"))); // NOI18N

        }
        else if(temperature<40&&temperature>=30){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Termometro/IMAGENES/3.png"))); // NOI18N
        }
        else{
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Termometro/IMAGENES/4.png"))); // NOI18N

        }
    }
    public double getTemperature(){return temperature;}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Termometro/IMAGENES/1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
